"""empty message

Revision ID: 41f61fdb44a6
Revises: None
Create Date: 2015-06-15 23:32:25.094120

"""

# revision identifiers, used by Alembic.
revision = '41f61fdb44a6'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gtfs_agency',
    sa.Column('agency_id', sa.Integer(), nullable=False),
    sa.Column('agency_name', sa.String(), nullable=True),
    sa.Column('agency_url', sa.String(), nullable=True),
    sa.Column('agency_timezone', sa.String(), nullable=True),
    sa.Column('agency_lang', sa.String(), nullable=True),
    sa.Column('agency_phone', sa.String(), nullable=True),
    sa.Column('agency_fare_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('agency_id')
    )
    op.create_table('gtfs_calendar',
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('monday', sa.Integer(), nullable=True),
    sa.Column('tuesday', sa.Integer(), nullable=True),
    sa.Column('wednesday', sa.Integer(), nullable=True),
    sa.Column('thursday', sa.Integer(), nullable=True),
    sa.Column('friday', sa.Integer(), nullable=True),
    sa.Column('saturday', sa.Integer(), nullable=True),
    sa.Column('sunday', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('service_id')
    )
    op.create_table('gtfs_calendar_dates',
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('exception_date', sa.Date(), nullable=False),
    sa.Column('exception_type', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('service_id', 'exception_date', 'exception_type')
    )
    op.create_table('gtfs_routes',
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.Column('agency_id', sa.Integer(), nullable=True),
    sa.Column('route_short_name', sa.String(), nullable=True),
    sa.Column('route_long_name', sa.String(), nullable=True),
    sa.Column('route_desc', sa.String(), nullable=True),
    sa.Column('route_type', sa.Integer(), nullable=True),
    sa.Column('route_url', sa.String(), nullable=True),
    sa.Column('route_color', sa.String(), nullable=True),
    sa.Column('route_text_color', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('route_id')
    )
    op.create_table('gtfs_shapes',
    sa.Column('shape_id', sa.Integer(), nullable=False),
    sa.Column('shape_pt_lat', sa.Float(), nullable=True),
    sa.Column('shape_pt_lon', sa.Float(), nullable=True),
    sa.Column('shape_pt_sequence', sa.Integer(), nullable=False),
    sa.Column('shape_dist_traveled', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('shape_id', 'shape_pt_sequence')
    )
    op.create_table('gtfs_stop_times',
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('arrival_time', sa.String(), nullable=True),
    sa.Column('departure_time', sa.String(), nullable=True),
    sa.Column('stop_id', sa.Integer(), nullable=False),
    sa.Column('stop_sequence', sa.Integer(), nullable=False),
    sa.Column('stop_headsign', sa.String(), nullable=True),
    sa.Column('pickup_type', sa.String(), nullable=True),
    sa.Column('drop_off_type', sa.String(), nullable=True),
    sa.Column('shape_dist_traveled', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('trip_id', 'stop_id', 'stop_sequence')
    )
    op.create_table('gtfs_stops',
    sa.Column('stop_id', sa.Integer(), nullable=False),
    sa.Column('stop_code', sa.String(), nullable=True),
    sa.Column('stop_name', sa.String(), nullable=True),
    sa.Column('stop_desc', sa.String(), nullable=True),
    sa.Column('stop_lat', sa.Float(), nullable=True),
    sa.Column('stop_lon', sa.Float(), nullable=True),
    sa.Column('zone_id', sa.Float(), nullable=True),
    sa.Column('stop_url', sa.Float(), nullable=True),
    sa.Column('location_type', sa.Integer(), nullable=True),
    sa.Column('parent_station', sa.Integer(), nullable=True),
    sa.Column('stop_timezone', sa.String(), nullable=True),
    sa.Column('wheelchair_boarding', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('stop_id')
    )
    op.create_table('gtfs_trips',
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=True),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('trip_headsign', sa.String(), nullable=True),
    sa.Column('trip_short_name', sa.String(), nullable=True),
    sa.Column('direction_id', sa.Integer(), nullable=True),
    sa.Column('block_id', sa.Integer(), nullable=True),
    sa.Column('shape_id', sa.Integer(), nullable=True),
    sa.Column('wheelchair_accessible', sa.Boolean(), nullable=True),
    sa.Column('bikes_allowed', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('route_id', 'trip_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gtfs_trips')
    op.drop_table('gtfs_stops')
    op.drop_table('gtfs_stop_times')
    op.drop_table('gtfs_shapes')
    op.drop_table('gtfs_routes')
    op.drop_table('gtfs_calendar_dates')
    op.drop_table('gtfs_calendar')
    op.drop_table('gtfs_agency')
    ### end Alembic commands ###
